config/routes.rb
Rails.application.routes.draw do
	resources :books
	root :to => "books#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def create
  	@books = Book.all
  	@book = Book.new(book_params)
  	if @book.save
	  	flash[:notice] = "Book was successfully created."
	  	redirect_to book_path(@book.id)
	else
		render "books/index"
	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(params[:id])
  		flash[:notice] = "Book was successfully updated."
  	else
  		render "books/edit"
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
	<p class="error">[error]can't be blank</p>
<% end %>
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<br>
	<%= f.submit "Update Book" %>
	<p>
		<%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>
	</p>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
	<tr>
		<th>Title</th>
		<th>Body</th>
		<th></th>
	</tr>
	<% @books.each do |book| %>
	<tr>
		<td><%= book.title %></td>
		<td><%= book.body %></td>
		<td><%= link_to "Show", book_path(book.id) %></td>
		<td><%= link_to "Edit", edit_book_path(book.id) %></td>
		<td><%= link_to "Destroy", book_path(book.id), method: :delete, data: {confirm: "削除しますか?"} %></td>
	</tr>
	<% end %>
</table>

<h1>New book</h1>
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
	<p class="error">[error]can't be blank</p>
<% end %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<br>
	<%= f.submit "Create Book" %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_for(@book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<br>
	<%= f.submit "Cerate Book" %>
<% end %>

app/views/books/show.html.erb
<p class="notice">
	<%= notice %>
</p>
<p>Title: <%= @book.title %></p>
<p>Body: <%= @book.body %></p>
<p>
	<%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Back", books_path %>
</p>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ!</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
	印象を共有し交換することができます
</p>
<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>